---
title: "statistical learning"
author: "Mukta Patwari"
date: "2025-11-20"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages

```{r}
library(tidyverse)
library(glmnet)

set.seed(11)
```

## Do LASSO
```{r}
bwt_df = 
  read_csv("data/birthweight.csv") |> 
  janitor::clean_names() |>
  mutate(
    babysex = 
        case_match(babysex,
            1 ~ "male",
            2 ~ "female"
        ),
    babysex = fct_infreq(babysex),
    frace = 
        case_match(frace,
            1 ~ "white",
            2 ~ "black", 
            3 ~ "asian", 
            4 ~ "puerto rican", 
            8 ~ "other"),
    frace = fct_infreq(frace),
    mrace = 
        case_match(mrace,
            1 ~ "white",
            2 ~ "black", 
            3 ~ "asian", 
            4 ~ "puerto rican",
            8 ~ "other"),
    mrace = fct_infreq(mrace),
    malform = as.logical(malform)) |> 
  sample_n(200)
```

Data processing

```{r}
x = model.matrix(bwt ~ ., bwt_df)
y = bwt_df %>% pull(bwt)
```

Define some lambdas and fit Lasso for each

```{r}
lambda = 10^(seq(-2, 2.75, 0.1))

lasso_fit =
  glmnet(x = x, y = y, lambda = lambda)

lasso_cv =
  cv.glmnet(x = x, y = y, lambda = lambda)

lambda_opt = lasso_cv[["lambda.min"]]
```

Evaluate what is happening in lasso_fit

```{r}
lasso_fit %>% 
  broom::tidy() %>% 
  select(term, lambda, estimate) %>% 
  complete(term, lambda, fill = list(estimate = 0)) %>%
  filter(term != "Intercept") %>% 
  ggplot(aes(x = log(lambda, 10), y = estimate, group = term, color = term)) +
  geom_line() +
  geom_vline(xintercept = log(lambda_opt, 10))
```

Plot 2

```{r}
lasso_cv %>% 
  broom::tidy() %>% 
  ggplot(aes(x = log(lambda, 10), y = estimate)) +
  geom_point()
```

